# Generated by Django 4.2.6 on 2023-11-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=255, verbose_name='Марка')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('description', models.TextField(max_length=255, verbose_name='Описание')),
                ('link', models.URLField(verbose_name='Ссылка на объявление')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('sold', models.BooleanField(verbose_name='Продано')),
            ],
        ),
    ]
