# Generated by Django 4.2.6 on 2023-11-08 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Sneakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('size', models.IntegerField(verbose_name='Размер')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('base_price', models.IntegerField(verbose_name='Базовая цена')),
                ('sale', models.IntegerField(verbose_name='Скидка')),
                ('stock', models.BooleanField(verbose_name='Наличие')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.category', verbose_name='Категория')),
            ],
        ),
    ]
